terraform:
  plan:
    disable_label: false
    when_add_or_update_only:
      label: "add-or-update"
    when_destroy:
      label: "destroy"
    when_no_changes:
      label: "no-changes"
    when_plan_error:
      label: "plan-error"
      label_color: d93f0b # red
